import { AppState, Issue, Priority, Project, Sprint, User } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Rivera', email: 'alex@flowsync.com', avatarUrl: 'https://picsum.photos/100/100?random=1' },
  { id: 'u2', name: 'Sarah Chen', email: 'sarah@flowsync.com', avatarUrl: 'https://picsum.photos/100/100?random=2' },
  { id: 'u3', name: 'Mike Johnson', email: 'mike@flowsync.com', avatarUrl: 'https://picsum.photos/100/100?random=3' },
  { id: 'u4', name: 'Emily Davis', email: 'emily@flowsync.com', avatarUrl: 'https://picsum.photos/100/100?random=4' },
];

export const MOCK_PROJECTS: Project[] = [
  { id: 'p1', key: 'FLOW', name: 'FlowSync Core', description: 'Main application development', leadId: 'u1', avatarUrl: 'https://picsum.photos/200/200?random=5' },
];

export const MOCK_SPRINTS: Sprint[] = [
  { id: 's1', name: 'Sprint 23', startDate: '2023-10-01', endDate: '2023-10-14', goal: 'Implement core board features', isActive: true, isCompleted: false },
  { id: 's2', name: 'Sprint 24', startDate: '2023-10-15', endDate: '2023-10-29', goal: 'Backlog refinement and polish', isActive: false, isCompleted: false },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'i1',
    key: 'FLOW-1',
    title: 'Setup React Project Structure',
    description: 'Initialize the repository with React, TypeScript, and Tailwind.',
    type: 'Task',
    status: 'Done',
    priority: 'High',
    assigneeId: 'u1',
    reporterId: 'u1',
    sprintId: 's1',
    storyPoints: 3,
    linkedIssueIds: [],
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-02T14:00:00Z',
    comments: [],
  },
  {
    id: 'i2',
    key: 'FLOW-2',
    title: 'Implement Kanban Board Drag and Drop',
    description: 'Users should be able to drag issues between columns.',
    type: 'Story',
    status: 'In Progress',
    priority: 'Highest',
    assigneeId: 'u2',
    reporterId: 'u1',
    sprintId: 's1',
    storyPoints: 8,
    linkedIssueIds: ['i1'],
    createdAt: '2023-10-01T11:00:00Z',
    updatedAt: '2023-10-03T09:00:00Z',
    comments: [
      { id: 'c1', userId: 'u3', content: 'Should we use a library for this?', createdAt: '2023-10-03T10:00:00Z' }
    ],
  },
  {
    id: 'i3',
    key: 'FLOW-3',
    title: 'Fix avatar alignment in header',
    description: 'The user avatar is slightly off-center in the top navigation bar.',
    type: 'Bug',
    status: 'To Do',
    priority: 'Low',
    assigneeId: 'u1',
    reporterId: 'u2',
    sprintId: 's1',
    storyPoints: 1,
    linkedIssueIds: [],
    createdAt: '2023-10-04T16:00:00Z',
    updatedAt: '2023-10-04T16:00:00Z',
    comments: [],
  },
  {
    id: 'i4',
    key: 'FLOW-4',
    title: 'Design System Documentation',
    description: 'Create initial documentation for color palette and typography.',
    type: 'Task',
    status: 'In Review',
    priority: 'Medium',
    assigneeId: 'u4',
    reporterId: 'u1',
    sprintId: 's1',
    storyPoints: 5,
    linkedIssueIds: [],
    createdAt: '2023-10-02T13:00:00Z',
    updatedAt: '2023-10-05T11:00:00Z',
    comments: [],
  },
  {
    id: 'i5',
    key: 'FLOW-5',
    title: 'Backend API for User Auth',
    description: 'Implement JWT based authentication endpoints.',
    type: 'Story',
    status: 'To Do',
    priority: 'High',
    assigneeId: 'u3',
    reporterId: 'u1',
    sprintId: 's2',
    storyPoints: 8,
    linkedIssueIds: ['i1'],
    createdAt: '2023-10-05T09:00:00Z',
    updatedAt: '2023-10-05T09:00:00Z',
    comments: [],
  },
    {
    id: 'i6',
    key: 'FLOW-6',
    title: 'Optimize Database Queries',
    description: 'The dashboard loading time is increasing. Need to index the issues table.',
    type: 'Task',
    status: 'To Do',
    priority: 'Highest',
    assigneeId: 'u2',
    reporterId: 'u3',
    sprintId: 's1',
    storyPoints: 5,
    linkedIssueIds: [],
    createdAt: '2023-10-06T09:00:00Z',
    updatedAt: '2023-10-06T09:00:00Z',
    comments: [],
  },
];

export const INITIAL_STATE: AppState = {
  currentUser: MOCK_USERS[0],
  users: MOCK_USERS,
  projects: MOCK_PROJECTS,
  issues: MOCK_ISSUES,
  sprints: MOCK_SPRINTS,
  currentProjectId: 'p1',
};